<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "homework1";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                // 1. Insertar Credentials primero (usuario y contraseña para autenticación)
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'demo', 'demo')",
                
                // 2. Insertar Modelos de prueba (2 privados, 2 públicos)
                // Modelo privado 1: GPT-4 (OpenAI)
                "INSERT INTO " + schema + ".MODEL VALUES (NEXT VALUE FOR MODEL_GEN, 'GPT-4.1-mini', 'OpenAI', 'Modelo optimizado para conversaciones rápidas con costes reducidos', 'GPT-4.1-mini es la versión compacta diseñada para aplicaciones rápidas', 'Custom', 32768, true, 'https://openai.com/favicon.ico', '2025-06-10', '2024-07-01', '2025-07-01')",
                
                // Modelo privado 2: Claude (Anthropic)
                "INSERT INTO " + schema + ".MODEL VALUES (NEXT VALUE FOR MODEL_GEN, 'Claude 3.5 Sonnet', 'Anthropic', 'Modelo avanzado con capacidades superiores en razonamiento y código', 'Claude 3.5 Sonnet combina velocidad y precisión en tareas complejas', 'Custom', 200000, true, 'https://anthropic.com/favicon.ico', '2025-08-15', '2024-09-01', '2025-08-15')",
                
                // Modelo público 1: Mistral (Mistral AI)
                "INSERT INTO " + schema + ".MODEL VALUES (NEXT VALUE FOR MODEL_GEN, 'Mistral Large 2', 'Mistral AI', 'Modelo open-source de alto rendimiento con licencia Apache 2.0', 'Mistral Large 2 ofrece rendimiento competitivo completamente abierto', 'Apache 2.0', 128000, false, 'https://mistral.ai/favicon.ico', '2025-05-20', '2024-06-01', '2025-05-20')",
                
                // Modelo público 2: LLaMA (Meta)
                "INSERT INTO " + schema + ".MODEL VALUES (NEXT VALUE FOR MODEL_GEN, 'LLaMA 3.1', 'Meta', 'Modelo open-source optimizado para multilingüe y razonamiento', 'LLaMA 3.1 con mejoras en capacidades multilingües y razonamiento', 'Permissive Open Source', 128000, false, 'https://llama.meta.com/favicon.ico', '2025-04-30', '2024-05-15', '2025-04-30')",
                
                // Insertar capabilities para cada modelo (tabla auxiliar MODEL_CAPABILITIES)
                // GPT-4
                "INSERT INTO " + schema + ".MODEL_CAPABILITIES VALUES (1, 'chat-completion')",
                "INSERT INTO " + schema + ".MODEL_CAPABILITIES VALUES (1, 'code-generation')",
                "INSERT INTO " + schema + ".MODEL_CAPABILITIES VALUES (1, 'text-summarization')",
                
                // Claude
                "INSERT INTO " + schema + ".MODEL_CAPABILITIES VALUES (2, 'chat-completion')",
                "INSERT INTO " + schema + ".MODEL_CAPABILITIES VALUES (2, 'code-generation')",
                "INSERT INTO " + schema + ".MODEL_CAPABILITIES VALUES (2, 'reasoning')",
                
                // Mistral
                "INSERT INTO " + schema + ".MODEL_CAPABILITIES VALUES (3, 'chat-completion')",
                "INSERT INTO " + schema + ".MODEL_CAPABILITIES VALUES (3, 'code-generation')",
                
                // LLaMA
                "INSERT INTO " + schema + ".MODEL_CAPABILITIES VALUES (4, 'chat-completion')",
                "INSERT INTO " + schema + ".MODEL_CAPABILITIES VALUES (4, 'multilingual')",
                "INSERT INTO " + schema + ".MODEL_CAPABILITIES VALUES (4, 'reasoning')",
                
                // Insertar inputTypes para cada modelo (tabla auxiliar MODEL_INPUT_TYPES)
                "INSERT INTO " + schema + ".MODEL_INPUT_TYPES VALUES (1, 'text')",
                "INSERT INTO " + schema + ".MODEL_INPUT_TYPES VALUES (2, 'text')",
                "INSERT INTO " + schema + ".MODEL_INPUT_TYPES VALUES (2, 'image')",
                "INSERT INTO " + schema + ".MODEL_INPUT_TYPES VALUES (3, 'text')",
                "INSERT INTO " + schema + ".MODEL_INPUT_TYPES VALUES (4, 'text')",
                
                // Insertar outputTypes para cada modelo (tabla auxiliar MODEL_OUTPUT_TYPES)
                "INSERT INTO " + schema + ".MODEL_OUTPUT_TYPES VALUES (1, 'text')",
                "INSERT INTO " + schema + ".MODEL_OUTPUT_TYPES VALUES (2, 'text')",
                "INSERT INTO " + schema + ".MODEL_OUTPUT_TYPES VALUES (3, 'text')",
                "INSERT INTO " + schema + ".MODEL_OUTPUT_TYPES VALUES (4, 'text')",
                
                // 3. Insertar Customers (vinculados a Credentials mediante FK)
                // NOTA: credentials_id debe coincidir con el ID de Credentials insertado arriba
                "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 1, 3)",  // sob vio Mistral (modelo público id=3)
                "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 2, NULL)"  // demo no ha visto nada todavía
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
