<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "homework1";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                // 1. Insertar Credentials primero (usuario y contraseña para autenticación)
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'demo', 'demo')",
                
                // 2. Insertar Modelos de prueba (2 privados, 2 públicos)
                // Modelo privado 1: GPT-4 (OpenAI)
                "INSERT INTO " + schema + ".MODEL (ID, NAME, PROVIDER, SUMMARY, DESCRIPTION, LICENSE, MAXCONTEXTTOKENS, ISPRIVATE, LOGOURL, LASTVERSION, TRAININGDATE, LASTUPDATEDATE) VALUES (NEXT VALUE FOR MODEL_GEN, 'GPT-4.1-mini', 'OpenAI', 'Modelo optimizado para conversaciones rápidas con costes reducidos', 'GPT-4.1-mini es la versión compacta diseñada para aplicaciones rápidas', 'Custom', 32768, 1, 'https://openai.com/favicon.ico', '2025-06-10', DATE('2024-07-01'), DATE('2025-07-01'))",
                
                // Modelo privado 2: Claude (Anthropic)
                "INSERT INTO " + schema + ".MODEL (ID, NAME, PROVIDER, SUMMARY, DESCRIPTION, LICENSE, MAXCONTEXTTOKENS, ISPRIVATE, LOGOURL, LASTVERSION, TRAININGDATE, LASTUPDATEDATE) VALUES (NEXT VALUE FOR MODEL_GEN, 'Claude 3.5 Sonnet', 'Anthropic', 'Modelo avanzado con capacidades superiores en razonamiento y código', 'Claude 3.5 Sonnet combina velocidad y precisión en tareas complejas', 'Custom', 200000, 1, 'https://anthropic.com/favicon.ico', '2025-08-15', DATE('2024-09-01'), DATE('2025-08-15'))",
                
                // Modelo público 1: Mistral (Mistral AI)
                "INSERT INTO " + schema + ".MODEL (ID, NAME, PROVIDER, SUMMARY, DESCRIPTION, LICENSE, MAXCONTEXTTOKENS, ISPRIVATE, LOGOURL, LASTVERSION, TRAININGDATE, LASTUPDATEDATE) VALUES (NEXT VALUE FOR MODEL_GEN, 'Mistral Large 2', 'Mistral AI', 'Modelo open-source de alto rendimiento con licencia Apache 2.0', 'Mistral Large 2 ofrece rendimiento competitivo completamente abierto', 'Apache 2.0', 128000, 0, 'https://mistral.ai/favicon.ico', '2025-05-20', DATE('2024-06-01'), DATE('2025-05-20'))",
                
                // Modelo público 2: LLaMA (Meta)
                "INSERT INTO " + schema + ".MODEL (ID, NAME, PROVIDER, SUMMARY, DESCRIPTION, LICENSE, MAXCONTEXTTOKENS, ISPRIVATE, LOGOURL, LASTVERSION, TRAININGDATE, LASTUPDATEDATE) VALUES (NEXT VALUE FOR MODEL_GEN, 'LLaMA 3.1', 'Meta', 'Modelo open-source optimizado para multilingüe y razonamiento', 'LLaMA 3.1 con mejoras en capacidades multilingües y razonamiento', 'Permissive Open Source', 128000, 0, 'https://llama.meta.com/favicon.ico', '2025-04-30', DATE('2024-05-15'), DATE('2025-04-30'))",
                
                // 3. Insertar Customers (vinculados a Credentials mediante FK)
                // NOTA: credentials_id debe coincidir con el ID de Credentials insertado arriba
                "INSERT INTO " + schema + ".CUSTOMER (ID, CREDENTIALS_ID, ULTIMO_MODELO_VISITADO_ID, TELEFONO) VALUES (NEXT VALUE FOR CUSTOMER_GEN, (SELECT ID FROM " + schema + ".CREDENTIALS WHERE USERNAME='sob'), (SELECT ID FROM " + schema + ".MODEL WHERE NAME='Mistral Large 2'), '+34612345678')",
                "INSERT INTO " + schema + ".CUSTOMER (ID, CREDENTIALS_ID, TELEFONO) VALUES (NEXT VALUE FOR CUSTOMER_GEN, (SELECT ID FROM " + schema + ".CREDENTIALS WHERE USERNAME='demo'), '+34698765432')"
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
